//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MFCApplication5.rc 使用
//
#define IDAddObstacleC                  3
#define IDDeleteObstacleC               4
#define IDSObstacleCInput               5
#define IDSObstacleCOutput              6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_USVTYPE                     130
#define ID_WINDOW_MANAGER               131
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_Set_start_goal_Position     310
#define IDD_SetStaticObstacleCircle     311
#define IDR_MANIFEST                    313
#define IDD_SetViewSize                 316
#define IDB_googleicon                  326
#define IDB_googleiconSmall             333
#define IDC_StartX                      1000
#define IDC_StartY                      1001
#define IDC_GoalX                       1002
#define IDC_EDIT4                       1003
#define IDC_GoalY                       1003
#define IDC_Change                      1003
#define IDC_StaticObstacleR             1004
#define IDC_PSOsetV_numMAX              1005
#define IDC_GoalY2                      1005
#define IDC_PSOsetInitialV              1006
#define IDC_LIST_StaticObstacle         1018
#define IDD_SetPSO                      1020
#define IDC_StaticObstacleX             1021
#define IDD_SetStaticObstacleRectangle  1021
#define IDC_StaticObstacleY             1022
#define IDD_SetDynamicOC                1022
#define IDC_PSOgenerations              1023
#define IDC_StaticObstacleCY            1023
#define IDD_SetDynamicOR                1023
#define IDC_PSOparticle_num             1024
#define IDC_StaticObstacleHL            1024
#define IDC_LIST_StaticObstacleaRectangle 1025
#define IDC_StaticObstacleHW            1026
#define IDC_StaticObstacleDA            1027
#define IDC_StaticObstacleCX            1028
#define IDAddObstacleR                  1029
#define IDDeleteObstacleR               1030
#define IDSObstacleCInputR              1031
#define IDSObstacleCOutputR             1032
#define IDC_DynamicOR_V                 1033
#define IDC_SetViewLength               1034
#define IDC_SetViewWidth                1035
#define IDC_DynamicOC_X                 1037
#define IDC_DynamicOC_Y                 1038
#define IDC_DynamicOC_R                 1039
#define IDC_DynamicOC_DA                1040
#define IDC_DynamicOC_V                 1041
#define IDAddDynamicOC                  1042
#define IDDeleteDynamicOC               1043
#define IDSDynamicOCIutput              1045
#define IDSDynamicOCOutputC             1046
#define IDC_LIST_DynamicOC              1047
#define IDC_DynamicOR_X                 1048
#define IDC_DynamicOR_Y                 1049
#define IDC_DynamicOR_HL                1050
#define IDC_DynamicOR_HW                1051
#define IDC_DynamicOR_DA                1052
#define IDC_LIST_DynamicOR              1053
#define IDAddDynamicOR                  1054
#define IDDeleteDynamicOR               1055
#define IDSDynamicORInput               1056
#define IDSDynamicOROutput              1057
#define IDC_PSOchangeDO                 1058
#define IDC_PSOgenerationsDO            1062
#define IDC_PSOparticle_numDO           1063
#define IDC_PSOchangeV                  1064
#define IDC_PSOchangeDa                 1065
#define IDC_LIST_UnknownOC              1066
#define IDC_UnknownOC_X                 1067
#define IDC_UnknownOC_Y                 1068
#define IDC_Unknown_R                   1069
#define IDD_SetDoPSO                    1070
#define IDC_Unknown_DA                  1070
#define IDD_SetUnknownOC                1071
#define IDC_Unknown_V                   1071
#define IDD_SetUnknownOR                1072
#define IDAddUnknownOC                  1072
#define IDDeleteUnknownOC               1073
#define IDD_Set_start_goal_Position1    1073
#define IDD_Set_Unknown                 1073
#define IDSUnknownOCIutput              1074
#define IDSUnknownOCOutput              1075
#define IDC_UnknownOR_X                 1076
#define IDC_UnknownOR_Y                 1077
#define IDC_UnknownOR_HL                1078
#define IDC_UnknownOR_HW                1079
#define IDC_UnknownOR_DA                1080
#define IDC_UnknownOR_V                 1081
#define IDAddUnknownOR                  1082
#define IDDeleteUnknownOR               1083
#define IDSUnknownORInput               1084
#define IDSUnknownOROutput              1085
#define IDC_LIST_UnknownOR              1086
#define IDC_UnknownR                    1087
#define IDC_UnknownL                    1088
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CalculatePSO                 32772
#define ID_Set_start_goal_Position      32773
#define ID_SetStaticObstacleCircle      32774
#define ID_BUTTON2                      32775
#define ID_SetDynamicOC                 32775
#define ID_SetStaticObstacleRectangle   32776
#define ID_COMBOstartgoal               32777
#define ID_SetUnknownOC                 32778
#define ID_COMBO_SOC                    32780
#define ID_BT_setPSO                    32783
#define ID_CalculateAndOptimize         32784
#define ID_OptimizePath                 32786
#define ID_setPSOdo                     32787
#define ID_COMBO_PathPoint              32788
#define ID_CalculateDO_PSO              32789
#define ID_SetPSO                       32790
#define ID_DataOUTPUT                   32791
#define ID_SetViewSize                  32799
#define ID_SetDynamicOR                 32800
#define ID_COMBO_ViewInformation        32801
#define ID_COMBO_DO                     32802
#define ID_COMBO_DOun                   32803
#define ID_VIEWdo                       32804
#define ID_SetUNKNOWN                   32807
#define ID_BUTTON7                      32808
#define ID_SetUnknownOR                 32809
#define ID_CalculateUnknown             32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        334
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
